name: runs after Preflight is completed
on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
jobs:
  test-workflow_run:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: echo "runs after Preflight is completed"
