name: Parallel Jobs
run-name: Parallel Jobs Test by @${{ github.actor }} # Name to be displayed in the list of workflow runs on your repository's "Actions"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "run-shell-command"
  run-shell-command:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # echo a string
      - run: echo "Hello World"
  # This is a parallel job
  run-windows-command:
    runs-on: windows-latest
    # Running a powershell command in windows
    steps:
      - name: Directory Powershell
        run: start-sleep -seconds 300
        
