name: Preflight
on:
  - workflow_dispatch
jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "initial workflow"
      - run: echo ${{ github.workflow }}-${{ github.ref }}
