name: Depends on - Jobs
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
# push:
#   branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# In this case "run-shell-command" and "run-windows-command" will run in parallel
jobs:
  # This workflow contains a job called "run-shell-command"
  run-shell-command:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # echo a string
      - run: echo "Hello World"
  # This is a depending job
  run-windows-command:
    runs-on: windows-latest
    # we tells here that this job depends of the previous one
    needs: ['run-shell-command']
    # Running a powershell command in windows
    steps:
      - name: Directory Powershell
        run: Get-Location
